TRUNCATE TABLE schedule;
TRUNCATE TABLE hall_grade;
TRUNCATE TABLE album;
TRUNCATE TABLE seller;
DELETE FROM performance;
DELETE FROM hall;
DELETE FROM grade;
DELETE FROM singer;
DELETE FROM company;


