pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // 코드 체크아웃
                    checkout scm
                }
            }
        }

        stage('Build Discovery-Server .JAR') {
            steps {
                script {
                    echo "discovery server 입니다."
                }
            }
        }
    }
}
